should not require json serializer unless it is configured.
SpiffInc/polyn-ruby pull request #6
Opened 2022-02-10 02:08 UTC by fugufish

this isn't really testable, its more of a require/loading detail

2022-02-24 06:31 UTC, reecebisel requested changes

2022-02-24 06:31 UTC, reecebisel commented on lib/polyn/application.rb
I do not like this styling change. It doesn't change anything. But I am not a fan.

2022-02-24 06:31 UTC, reecebisel commented on lib/polyn/application.rb
> +        pass
Why was this changed to pass?

2022-02-24 06:31 UTC, reecebisel commented on lib/polyn/application.rb
> +        end
This should be moved to a private method. Its an implementation detail. I am not a huge fan of case statements for this reason.

2022-02-24 06:31 UTC, reecebisel commented on lib/polyn/reactor_manager.rb
> +    end
Any reason for keeping this inside the reactor manager file?

2022-02-24 06:31 UTC, reecebisel commented on lib/polyn/reactor_manager.rb
> +      Wrapper.new(super(:reactor_manager, services))
Would we need to do some sort of memorization around this?

2022-02-24 06:31 UTC, reecebisel commented on lib/polyn/serializers.rb
> +        require "polyn/serializers/json"
Why though?

2022-02-24 06:31 UTC, reecebisel commented on lib/polyn/transit.rb
> +        end
ditts on the private method.

2022-02-24 06:31 UTC, reecebisel commented on lib/polyn/transit.rb
> +      @events ||= reactor_manager.reactors.map { |s| s.events.values }.flatten
Noice!

2022-02-24 06:31 UTC, reecebisel commented on lib/polyn/transit.rb
> +                                                   })
Ditts on the style change here.

2022-02-24 06:31 UTC, reecebisel commented on lib/polyn/transporters/internal.rb
> +        end
If we are calling this `polyn-ruby` we shouldn't be checking for rails. Otherwirse we should call this gem `polyn-rails`

2022-02-24 06:31 UTC, reecebisel commented on lib/polyn/utils/generic_concurrent_logger.rb
> +# frozen_string_literal: true
Do we have tests for this?

2022-08-05 23:06 UTC, brandynbennett commented
A lot has changes since this, so probably easier to close

2022-08-05 23:06 UTC, closed without merging